#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#  @generated
#

from libcpp.string cimport string
from libcpp cimport bool as cbool
from cpython cimport bool as pbool
from libc.stdint cimport int8_t, int16_t, int32_t, int64_t
from libcpp.memory cimport shared_ptr, unique_ptr
from libcpp.vector cimport vector
from libcpp.set cimport set as cset
from libcpp.map cimport map as cmap, pair as cpair
from thrift.lib.py3.thrift_server cimport cTException, TException


cdef extern from "src/gen-cpp2/module_types.h" namespace "cpp2":
    cdef cppclass cEmptyEnum "cpp2::EmptyEnum":
        bint operator==(cEmptyEnum&)
    cdef cppclass cCity "cpp2::City":
        bint operator==(cCity&)
    cCity City__NYC "cpp2::City::NYC"
    cCity City__MPK "cpp2::City::MPK"
    cCity City__SEA "cpp2::City::SEA"
    cCity City__LON "cpp2::City::LON"
    cdef cppclass cCompany "cpp2::Company":
        bint operator==(cCompany&)
    cCompany Company__FACEBOOK "cpp2::Company::FACEBOOK"
    cCompany Company__WHATSAPP "cpp2::Company::WHATSAPP"
    cCompany Company__OCULUS "cpp2::Company::OCULUS"
    cCompany Company__INSTAGRAM "cpp2::Company::INSTAGRAM"

cdef cEmptyEnum EmptyEnum_to_cpp(value)
cdef cCity City_to_cpp(value)
cdef cCompany Company_to_cpp(value)

cdef extern from "src/gen-cpp2/module_types.h" namespace "cpp2":
    cdef cppclass cInternship "cpp2::Internship":
        cInternship() except +
        int32_t weeks
        string title
        cCompany employer

    cdef cppclass cUnEnumStruct "cpp2::UnEnumStruct":
        cUnEnumStruct() except +
        cCity city

    cdef cppclass cRange "cpp2::Range":
        cRange() except +
        int32_t min
        int32_t max


cdef extern from "<utility>" namespace "std" nogil:
    cdef shared_ptr[cInternship] move(unique_ptr[cInternship])
    cdef shared_ptr[cUnEnumStruct] move(unique_ptr[cUnEnumStruct])
    cdef shared_ptr[cRange] move(unique_ptr[cRange])

cdef class Internship:
    cdef shared_ptr[cInternship] c_Internship

    @staticmethod
    cdef create(shared_ptr[cInternship] c_Internship)

cdef class UnEnumStruct:
    cdef shared_ptr[cUnEnumStruct] c_UnEnumStruct

    @staticmethod
    cdef create(shared_ptr[cUnEnumStruct] c_UnEnumStruct)

cdef class Range:
    cdef shared_ptr[cRange] c_Range

    @staticmethod
    cdef create(shared_ptr[cRange] c_Range)


