/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "thrift/compiler/test/fixtures/params/gen-cpp2/NestedContainers.h"

#include "thrift/compiler/test/fixtures/params/gen-cpp2/NestedContainers.tcc"

namespace cpp2 {

} // cpp2
namespace apache { namespace thrift {

}} // apache::thrift
