#!/bin/bash

set -e

javafoundations/scripts/create-idea-project \
--mode-files "mac" \
--project-root=thrift/lib/java \
//thrift/lib/java/common:common \
//thrift/lib/java/runtime:runtime \
//thrift/lib/java/runtime:runtime-test \
//thrift/lib/java/example/ping:ping-lib \
//thrift/lib/java/example/ping:ping-server \
//thrift/lib/java/example/ping:ping-client \
--verbose \
--non-interactive
