#!/bin/bash

set -e

javafoundations/scripts/create-idea-project \
--mode-files "mac" \
--project-root=thrift/lib/java \
//thrift/lib/java/common:common \
//thrift/lib/java/common:common-test \
//thrift/lib/java/runtime:runtime \
--verbose \
--non-interactive
