#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#  @generated
#
from libcpp.memory cimport shared_ptr


from my.namespacing.test.module.module.clients_wrapper cimport cTestServiceClientWrapper

cdef class TestService:
    cdef shared_ptr[cTestServiceClientWrapper] _module_TestService_client
    cdef object loop
    cdef object __weakref__

    @staticmethod
    cdef _module_TestService_set_client(TestService inst, shared_ptr[cTestServiceClientWrapper] c_obj)

