/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "module_constants.h"

namespace test_cpp2 { namespace cpp_reflection {

constexpr int32_t const module_constants::constant1_;
constexpr char const * const module_constants::constant2_;
constexpr  ::test_cpp2::cpp_reflection::enum1 const module_constants::constant3_;

}} // test_cpp2::cpp_reflection