/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package test.fixtures.sink;

import java.util.*;

public class SinkServiceAsyncReactiveWrapper 
    implements SinkService.Reactive {
    private final SinkService.Async _delegate;

    public SinkServiceAsyncReactiveWrapper(SinkService.Async _delegate) {
        
        this._delegate = _delegate;
    }

    @java.lang.Override
    public void close() {
        _delegate.close();
    }

}
