/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "thrift/compiler/test/fixtures/fatal-compat/gen-cpp2/module_constants.h"

namespace test_cpp2 { namespace cpp_reflection {

}} // test_cpp2::cpp_reflection
