/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package test.fixtures.annotation;

import java.util.*;

public class MyAnnotationServiceReactiveAsyncWrapper 
  implements MyAnnotationService.Async {
  private MyAnnotationService.Reactive _delegate;

  public MyAnnotationServiceReactiveAsyncWrapper(MyAnnotationService.Reactive _delegate) {
    
    this._delegate = _delegate;
  }

  @java.lang.Override
  public void close() {
    _delegate.close();
  }

  @java.lang.Override
  public com.google.common.util.concurrent.ListenableFuture<Void> ping() {
      return com.facebook.swift.transport.util.FutureUtil.toListenableFuture(_delegate.ping());
  }

}
