/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package test.fixtures.annotation;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import java.util.*;
import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.server.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;

@SwiftGenerated
@ThriftStruct(value="MyMapping", builder=MyMapping.Builder.class)
public final class MyMapping {
    @ThriftConstructor
    public MyMapping(
        @ThriftField(value=1, name="lsMap", requiredness=Requiredness.NONE) final com.foo.FastLongStringMap lsMap,
        @ThriftField(value=2, name="ioMap", requiredness=Requiredness.NONE) final com.foo.FastIntObjectMap<com.foo.FastIntLongMap> ioMap
    ) {
        this.lsMap = lsMap;
        this.ioMap = ioMap;
    }
    
    @ThriftConstructor
    protected MyMapping() {
      this.lsMap = null;
      this.ioMap = null;
    }
    
    public static class Builder {
        private com.foo.FastLongStringMap lsMap;
        @ThriftField(value=1, name="lsMap", requiredness=Requiredness.NONE)
        public Builder setLsMap(com.foo.FastLongStringMap lsMap) {
            this.lsMap = lsMap;
            return this;
        }
        private com.foo.FastIntObjectMap<com.foo.FastIntLongMap> ioMap;
        @ThriftField(value=2, name="ioMap", requiredness=Requiredness.NONE)
        public Builder setIoMap(com.foo.FastIntObjectMap<com.foo.FastIntLongMap> ioMap) {
            this.ioMap = ioMap;
            return this;
        }
    
        public Builder() { }
        public Builder(MyMapping other) {
            this.lsMap = other.lsMap;
            this.ioMap = other.ioMap;
        }
    
        @ThriftConstructor
        public MyMapping build() {
            return new MyMapping (
                this.lsMap,
                this.ioMap
            );
        }
    }
    
    private static final TStruct STRUCT_DESC = new TStruct("MyMapping");
    private final com.foo.FastLongStringMap lsMap;
    public static final int _LSMAP = 1;
    private static final TField LS_MAP_FIELD_DESC = new TField("lsMap", TType.MAP, (short)1);
    private final com.foo.FastIntObjectMap<com.foo.FastIntLongMap> ioMap;
    public static final int _IOMAP = 2;
    private static final TField IO_MAP_FIELD_DESC = new TField("ioMap", TType.MAP, (short)2);

    
    @ThriftField(value=1, name="lsMap", requiredness=Requiredness.NONE)
    public com.foo.FastLongStringMap getLsMap() { return lsMap; }
        
    @ThriftField(value=2, name="ioMap", requiredness=Requiredness.NONE)
    public com.foo.FastIntObjectMap<com.foo.FastIntLongMap> getIoMap() { return ioMap; }
    
    @Override
    public String toString() {
        return toStringHelper(this)
            .add("lsMap", lsMap)
            .add("ioMap", ioMap)
            .toString();
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        MyMapping other = (MyMapping)o;
    
        return
            Objects.equals(lsMap, other.lsMap) &&
            Objects.equals(ioMap, other.ioMap) &&
            true;
    }
    
    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {
            lsMap,
            ioMap
        });
    }
    
    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (this.lsMap != null) {
        oprot.writeFieldBegin(LS_MAP_FIELD_DESC);
        com.foo.FastLongStringMap _iter0 = this.lsMap;
        oprot.writeMapBegin(new TMap(TType.I64, TType.STRING, _iter0.size()));
        for (Map.Entry<Long, String> _iter1 : _iter0.entrySet()) {
          oprot.writeI64(_iter1.getKey());
          oprot.writeString(_iter1.getValue());
        }
        oprot.writeMapEnd();
        oprot.writeFieldEnd();
      }
      if (this.ioMap != null) {
        oprot.writeFieldBegin(IO_MAP_FIELD_DESC);
        com.foo.FastIntObjectMap<com.foo.FastIntLongMap> _iter0 = this.ioMap;
        oprot.writeMapBegin(new TMap(TType.I32, TType.MAP, _iter0.size()));
        for (Map.Entry<Integer, com.foo.FastIntLongMap> _iter1 : _iter0.entrySet()) {
          oprot.writeI32(_iter1.getKey());
          
          oprot.writeMapBegin(new TMap(TType.I32, TType.I64, _iter1.getValue().size()));
        for (Map.Entry<Integer, Long> _iter2 : _iter1.getValue().entrySet()) {
          oprot.writeI32(_iter2.getKey());
          oprot.writeI64(_iter2.getValue());
        }
        oprot.writeMapEnd();
        }
        oprot.writeMapEnd();
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
    
}
